/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;


import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
       
        setTitle("Para ti.");
    }

     
 public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Heart2.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonNO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Botonsi = new javax.swing.JButton();
        LabelFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 128));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonNO.setBackground(new java.awt.Color(255, 51, 51));
        BotonNO.setText("NO.");
        BotonNO.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonNOMouseMoved(evt);
            }
        });
        BotonNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNOActionPerformed(evt);
            }
        });
        getContentPane().add(BotonNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 70, 100, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("¿Quieres ser mi novia?");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 220, -1));

        Botonsi.setBackground(new java.awt.Color(0, 255, 0));
        Botonsi.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        Botonsi.setText("SÍ.");
        Botonsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonsiActionPerformed(evt);
            }
        });
        getContentPane().add(Botonsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 101, -1));

        LabelFoto.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        LabelFoto.setForeground(new java.awt.Color(0, 204, 204));
        LabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rosa.jpg"))); // NOI18N
        LabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(LabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNOMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNOMouseMoved
                 int x;
                 int y;
                 x = (int) (Math.random() * 350 + 20);
                 y = (int) (Math.random() * 85 + 30);
                 BotonNO.setBounds(x,y,100,30);
    }//GEN-LAST:event_BotonNOMouseMoved

    private void BotonsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonsiActionPerformed
         Osito ventanaosito = new Osito();
         ventanaosito.setVisible(true);
         this.setVisible(false);
           
             
            
    }//GEN-LAST:event_BotonsiActionPerformed

    private void BotonNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonNOActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         JOptionPane.showMessageDialog(null, "Hecho por Bigo#2182 (discord)");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonNO;
    private javax.swing.JButton Botonsi;
    private javax.swing.JLabel LabelFoto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
