/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author USUARIO
 */

import java.awt.Image;
import java.awt.Toolkit;
public class Osito extends javax.swing.JFrame {

    /**
     * Creates new form Osito
     */
    public Osito() {
        initComponents();
        this.setLocationRelativeTo(null);
         this.setResizable(false);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Heart2.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelAmor = new javax.swing.JLabel();
        labelosito = new javax.swing.JLabel();
        botonRegreso = new javax.swing.JButton();
        LabelWalpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Te amo uwu");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("¡Lo sabía! :D");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 120, 30));

        LabelAmor.setBackground(new java.awt.Color(153, 0, 153));
        LabelAmor.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        LabelAmor.setForeground(new java.awt.Color(255, 51, 255));
        LabelAmor.setText("Te amo :>");
        getContentPane().add(LabelAmor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 80, -1));

        labelosito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelosito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tenor.gif"))); // NOI18N
        labelosito.setText("jLabel1");
        getContentPane().add(labelosito, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 137, 135));

        botonRegreso.setBackground(new java.awt.Color(255, 0, 255));
        botonRegreso.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        botonRegreso.setForeground(new java.awt.Color(51, 255, 51));
        botonRegreso.setText("Regresar");
        botonRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresoActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        LabelWalpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(LabelWalpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresoActionPerformed
              Interfaz ventana1 = new Interfaz();
              ventana1.setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_botonRegresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Osito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Osito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Osito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Osito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Osito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAmor;
    private javax.swing.JLabel LabelWalpaper;
    private javax.swing.JButton botonRegreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelosito;
    // End of variables declaration//GEN-END:variables
}
